#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.source = ['main.cc']
    obj.target = 'audio-validator'
    obj.name   = 'audio-validator'
    obj.uselib = ['SNDFILE']
    obj.install_path = bld.env['LIBDIR']
